### ISSUE TITLE
All localEnv could not be loaded until vscode is quit then restarted

### ISSUE THREAD

**Issue by gitgithan** [RamiKrispin/vscode-python#3]
I'm refering to the 4 variables created using exports in zshrc and referenced by localEnv in `devcontainer.json`
```
export ENV_NAME=python_tutorial
export PYTHON_VER=3.10
export CSV_PATH=$HOME/Desktop/CSV
export MY_VAR=some_var
```
The most direct impact is `docker: Error response from daemon: invalid mount config for type "bind": field Source must not be empty. See 'docker run --help'.`
I'm not trying to specifically solve the bind mount issue, because that can be fixed by hardcoding. 

Before i restarted vscode, i tried to find answers in similar threads
1. https://github.com/microsoft/vscode-remote-release/issues/3456 (i'm using mac, not WSL2, but suspect that's irrelevant)
2. https://stackoverflow.com/questions/62986260/problem-loading-in-localenvtoken-into-devcontainer-json

What's the significance of quitting vscode then opening it again? (I'm on mac).
I thought just closing and opening a new terminal would already successfully load the env vars through zshrc (but it didn't work for me), and quitting entire vscode instance is unnecessary? (but had to be done to prevent reading unset empty values for the 4 variables. 

Interesting tidbit is when i hardcoded the CSV_PATH (while ignoring the other 3), the env got created as `python=`, only realized this silent fail when i did `conda env list` and saw how it messed up `conda create -y --name $ENV_NAME python=$PYTHON_VER` in `install_dependencies.sh`

**Comment by RamiKrispin** [comment]
Yes, VScode load and cache the environment variables when launching it. Therefore, if you add new environment variables, you will have to quit and reopen VScode to use those variables, as mentioned [here](https://github.com/RamiKrispin/vscode-python/blob/ed5380b1cceef8622123b7dd932b8de300882d7c/README.md?plain=1#L704)

**Comment by gitgithan** [comment]
When I read that statement I interpreted it as the terminal session. Are you refering to the whole running instance of vscode instead?
I did a test to check if env variables are updated.
1. env|sort
2. export ZZZ=1 to zshrc
3. exec zsh/close and restart terminal
4. env|sort

To see that step 4 has the new ZZZ=1 that step 1 did not have. 
Does this not prove that step 3 (No need to quit and restart entire vscode) is sufficient to have new env variables be picked up?
To clarify my issue again, I needed to restart the whole vscode, not just the terminal session using either of two step 3 methods to have devcontainers pickup those localEnv.

It sounds to me there are 2 separate layers of setup (zshrc setup, vscode cache) and devcontainers only looks at vscode cache. Please confirm this understanding?

I searched and can't find any details about a "vscode environment variables cache", do you have links to official sources/issue threads about how a vscode cache works? (i'm assuming that's a separate thing from shell setup done by zshrc)

**Comment by RamiKrispin** [comment]
I will reward it to make it clear. If you update your `zshrc` file with new environment variables while you have an open VScode session, those variables won't be available for that session until you close it and reopen it.

**Comment by RamiKrispin** [comment]
I update the note, hope this is clear now:
https://github.com/RamiKrispin/vscode-python/commit/9ce85128fc33dea1903251bc8a8f15df74ed9441
