### ISSUE TITLE
Error when re-opening folder with Dev Container

### ISSUE THREAD

**Issue by satishchhatpar** [RamiKrispin/vscode-python#4]
Error when re-opening folder with Dev Container

**Comment by satishchhatpar** [comment]
[dev-container-error.txt](https://github.com/RamiKrispin/vscode-python/files/12157141/dev-container-error.txt)

**Comment by RamiKrispin** [comment]
@satishchhatpar Are you trying to open the main folder or one of the examples? Also, what OS are you using?

**Comment by satishchhatpar** [comment]
@RamiKrispin sorry for late reply.
I tried opening one of the examples.
I'm using mac OS

**Comment by RamiKrispin** [comment]
@satishchhatpar, which examples are you trying to run? The first two examples can be executed from the terminal. You can launch example 3 with the Dev Container extension, but you will have to set `./examples/ex-3` as the main folder. Could you please check and let me know if this works for you?
